Example of using the pw2py module
===

Import the pw2py module (see instructions in the base repository README.md for installing pw2py)

In [8]:
# imports the pw2py module (instructions see README.md)
import pw2py as pw
import numpy as np

Using the atomgeo class

In [9]:
# create qeinp object, reading from a file "Si.sample.in"
geo = pw.atomgeo.from_file("Si.sample.in")

In [3]:
for ftype in ['qe', 'vasp', 'jdftx', 'xyz']:
    print(geo.__str__(ftype=ftype))
    print('-----------------')

&control
/
&system
    ibrav = 0
    ntyp = 1
    nat = 2
/
&electrons
/
CELL_PARAMETERS angstrom
        -2.714679092       0.000000000       2.714679092
         0.000000000       2.714679092       2.714679092
        -2.714679092       2.714679092       0.000000000
ATOMIC_POSITIONS crystal
    Si          0.000000000       0.000000000       0.000000000
    Si          0.250000000       0.250000000       0.250000000

-----------------
Generated from the PW2PY python module
1.0
        -2.714679092       0.000000000       2.714679092
         0.000000000       2.714679092       2.714679092
        -2.714679092       2.714679092       0.000000000
     Si
     2
direct
         0.000000000       0.000000000       0.000000000
         0.250000000       0.250000000       0.250000000

-----------------
# Generated from the PW2PY python module
lattice \
        -5.130000000       0.000000000      -5.130000000 \
         0.000000000       5.130000000       5.130000000 \
         5.130000000 

In [21]:
geo.pos_units = 'bohr'
geo.par_units = 'angstrom'
geo.par_units = 'bohr'
geo.pos_units = 'crystal'
geo.par_units = 'angstrom'
geo

atomgeo(ion = array(['Si', 'Si'], dtype='<U2'),par = array([[-2.71467909,  0.        ,  2.71467909],
       [ 0.        ,  2.71467909,  2.71467909],
       [-2.71467909,  2.71467909,  0.        ]]),pos = array([[0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25]]),par_units = 'angstrom',pos_units = 'crystal')

In [5]:
geo.__str__(ftype='test')

'&control\n/\n&system\n    ibrav = 0\n    ntyp = 1\n    nat = 2\n/\n&electrons\n/\nCELL_PARAMETERS bohr\n        -5.130000000       0.000000000       5.130000000\n         0.000000000       5.130000000       5.130000000\n        -5.130000000       5.130000000       0.000000000\nATOMIC_POSITIONS crystal\n    Si          0.000000000       0.000000000       0.000000000\n    Si          0.250000000       0.250000000       0.250000000\n'

In [34]:
# methods available for this object
[d for d in dir(geo) if not d.startswith('_')]

['change_units_par',
 'change_units_pos',
 'from_file',
 'ion',
 'nat',
 'par',
 'par_units',
 'pos',
 'pos_units',
 'sort_ions',
 'write_file',
 'write_jdftx',
 'write_vasp',
 'write_xyz']

In [35]:
# list of ions
geo.ion

['Si', 'Si']

In [36]:
# number of atoms
geo.nat

2

In [37]:
# array of cell parameters
geo.par

array([[-2.71467909,  0.        ,  2.71467909],
       [ 0.        ,  2.71467909,  2.71467909],
       [-2.71467909,  2.71467909,  0.        ]])

In [38]:
# array of atomic positions
geo.pos

array([[0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25]])

In [39]:
# str also looks good!
print(geo)

&control
/
&system
    ibrav = 0
    ntyp = 1
    nat = 2
/
&electrons
/
CELL_PARAMETERS angstrom
        -2.714679092       0.000000000       2.714679092
         0.000000000       2.714679092       2.714679092
        -2.714679092       2.714679092       0.000000000
ATOMIC_POSITIONS crystal
    Si          0.000000000       0.000000000       0.000000000
    Si          0.250000000       0.250000000       0.250000000



In [4]:
atoms = [['C', 'N', 'O'], [[1,1,1],[2,2,2],[3,4,5]]]
geo.add_atom(atoms)

In [5]:
print(geo)

&control
/
&system
    ibrav = 0
    ntyp = 4
    nat = 5
/
&electrons
/
CELL_PARAMETERS angstrom
        -2.714679092       0.000000000       2.714679092
         0.000000000       2.714679092       2.714679092
        -2.714679092       2.714679092       0.000000000
ATOMIC_POSITIONS bohr
    Si          0.000000000       0.000000000       0.000000000
    Si         -2.565000000       2.565000000       2.565000000
    C           1.000000000       1.000000000       1.000000000
    N           2.000000000       2.000000000       2.000000000
    O           3.000000000       4.000000000       5.000000000



In [6]:
geo.remove_indices([2,3,4])

In [7]:
print(geo)

&control
/
&system
    ibrav = 0
    ntyp = 1
    nat = 2
/
&electrons
/
CELL_PARAMETERS angstrom
        -2.714679092       0.000000000       2.714679092
         0.000000000       2.714679092       2.714679092
        -2.714679092       2.714679092       0.000000000
ATOMIC_POSITIONS bohr
    Si          0.000000000       0.000000000       0.000000000
    Si         -2.565000000       2.565000000       2.565000000



In [8]:
geo.replace_ion('Si', 'C')

In [9]:
print(geo)

&control
/
&system
    ibrav = 0
    ntyp = 1
    nat = 2
/
&electrons
/
CELL_PARAMETERS angstrom
        -2.714679092       0.000000000       2.714679092
         0.000000000       2.714679092       2.714679092
        -2.714679092       2.714679092       0.000000000
ATOMIC_POSITIONS bohr
    C           0.000000000       0.000000000       0.000000000
    C          -2.565000000       2.565000000       2.565000000



In [17]:
import numpy as np
P = np.array([[-1,1,-1],[-1,1,1],[1,1,-1]])

In [18]:
P.dot(geo.par)

array([[5.42935818, 0.        , 0.        ],
       [0.        , 5.42935818, 0.        ],
       [0.        , 0.        , 5.42935818]])

In [26]:
geo.pos.dot(geo.par)

array([[ 0.        ,  0.        ,  0.        ],
       [-1.35733955,  1.35733955,  1.35733955]])

In [40]:
iP = [1,2,3]
P = np.identity(3)
for i in range(3):
    P[i,i] = iP[i]

In [41]:
P.dot(geo.par)

array([[-2.71467909,  0.        ,  2.71467909],
       [ 0.        ,  5.42935818,  5.42935818],
       [-8.14403728,  8.14403728,  0.        ]])

In [43]:
if geo.pos_units == "crystal":
    for i in range(3):
        geo.pos[:,i] /= P[i,i]

In [45]:
geo.pos

array([[0.        , 0.        , 0.        ],
       [0.25      , 0.125     , 0.08333333]])

In [47]:
test = geo.pos
for i in range(3):
    for j in range(i):
        test[:,i] *= (j + 1)
    print(test)

[[0.         0.         0.        ]
 [0.25       0.125      0.08333333]]
[[0.         0.         0.        ]
 [0.25       0.125      0.08333333]]
[[0.         0.         0.        ]
 [0.25       0.125      0.16666667]]


In [3]:
sinp = pw.qeinp.from_file('Si.sample.in')

In [5]:
sinp.par_units

'angstrom'

In [17]:
sinp.pos[:,:3]

array([[0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25]])

In [22]:
[max(sinp.pos[:,i]) for i in range(3)]

[0.25, 0.25, 0.25]

In [25]:
[max(sinp.par[:,i]) for i in range(3)]

[0.0, 2.714679092, 2.714679092]

In [26]:
sinp.par

array([[-2.71467909,  0.        ,  2.71467909],
       [ 0.        ,  2.71467909,  2.71467909],
       [-2.71467909,  2.71467909,  0.        ]])

In [4]:
import mendeleev

In [5]:
mendeleev.element(55).symbol

'Cs'

In [2]:
geo = pw.atomgeo.from_file('../simple.xsf')

In [3]:
print(geo.__str__(ftype='xsf'))

# Generated from the PW2PY python module
DIM-GROUP
        3      1
PRIMVEC
         6.005378731       0.000000000       0.000000000
         0.000000000       6.005378731       0.000000000
         0.000000000       0.000000000       6.005378731
CONVVEC
         6.005378731       0.000000000       0.000000000
         0.000000000       6.005378731       0.000000000
         0.000000000       0.000000000       6.005378731
PRIMCOORD
        5      1
       55       0.000000000       0.000000000       0.000000000
       82       3.002688890       3.002688890       3.002688890
       35       0.000000000       3.002688890       3.002688890
       35       3.002688890       0.000000000       3.002688890
       35       3.002688890       3.002688890       0.000000000
CONVCOORD
        5      1
       55       0.000000000       0.000000000       0.000000000
       82       3.002688890       3.002688890       3.002688890
       35       0.000000000       3.002688890       3.002688890
       3

In [3]:
geo.write_file('geo.xsf')

In [4]:
P = np.array([1,2,3], dtype=int)
for i, par in enumerate(geo.par):
    print(par * P)

[-5.42935818  0.         16.28807455]
[ 0.         10.85871637 16.28807455]
[-5.42935818 10.85871637  0.        ]


In [22]:
test = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.multiply([[1],[2],[3]],test)

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [34]:
np.multiply(test, P.reshape(-1, 1))

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [33]:
print(geo.pos)
print(P.reshape(1, -1))
print(np.divide(geo.pos, P.reshape(1, -1)))

[[0.         0.         0.        ]
 [3.00268889 3.00268889 3.00268889]
 [0.         3.00268889 3.00268889]
 [3.00268889 0.         3.00268889]
 [3.00268889 3.00268889 0.        ]]
[[1 2 3]]
[[0.         0.         0.        ]
 [3.00268889 1.50134444 1.0008963 ]
 [0.         1.50134444 1.0008963 ]
 [3.00268889 0.         1.0008963 ]
 [3.00268889 1.50134444 0.        ]]


In [38]:
for i in range(P[0]):
    for j in range(P[1]):
        for k in range(P[2]):
            if i == j == k == 0: continue
            print (i,j,k)

0 0 1
0 0 2
0 1 0
0 1 1
0 1 2


In [41]:
int(1)/int(2)

0.5

In [43]:
1/P

array([1.        , 0.5       , 0.33333333])

In [3]:
geo.build_supercell([2,2,2])

[[0.    0.    0.   ]
 [0.125 0.125 0.125]]
[[0.  0.  0.5]]
[[0.    0.    0.   ]
 [0.125 0.125 0.125]]
[[0.  0.5 0. ]]
[[0.    0.    0.   ]
 [0.125 0.125 0.125]]
[[0.  0.5 0.5]]
[[0.    0.    0.   ]
 [0.125 0.125 0.125]]
[[0.5 0.  0. ]]
[[0.    0.    0.   ]
 [0.125 0.125 0.125]]
[[0.5 0.  0.5]]
[[0.    0.    0.   ]
 [0.125 0.125 0.125]]
[[0.5 0.5 0. ]]
[[0.    0.    0.   ]
 [0.125 0.125 0.125]]
[[0.5 0.5 0.5]]


In [5]:
geo.write_file('s222.vasp')

In [32]:
geo.qedict

AttributeError: 'atomgeo' object has no attribute 'qedict'

In [35]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [36]:
test = {'C':3}
test['N']

KeyError: 'N'